// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Movie struct {
	ID          int32
	Title       string
	Description string
	ReleaseDate time.Time
	Duration    int32
	CreatedAt   sql.NullTime
}
