// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (title, description, release_date, duration)
VALUES ($1, $2, $3, $4)
RETURNING id, title, description, release_date, duration
`

type CreateMovieParams struct {
	Title       string
	Description string
	ReleaseDate time.Time
	Duration    int32
}

type CreateMovieRow struct {
	ID          int32
	Title       string
	Description string
	ReleaseDate time.Time
	Duration    int32
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (CreateMovieRow, error) {
	row := q.db.QueryRowContext(ctx, createMovie,
		arg.Title,
		arg.Description,
		arg.ReleaseDate,
		arg.Duration,
	)
	var i CreateMovieRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ReleaseDate,
		&i.Duration,
	)
	return i, err
}

const deleteMovie = `-- name: DeleteMovie :exec
DELETE FROM movies
WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMovie, id)
	return err
}

const getMovieByID = `-- name: GetMovieByID :one
SELECT id, title, description, release_date, duration
FROM movies
WHERE id = $1
`

type GetMovieByIDRow struct {
	ID          int32
	Title       string
	Description string
	ReleaseDate time.Time
	Duration    int32
}

func (q *Queries) GetMovieByID(ctx context.Context, id int32) (GetMovieByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMovieByID, id)
	var i GetMovieByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ReleaseDate,
		&i.Duration,
	)
	return i, err
}

const listMovies = `-- name: ListMovies :many
SELECT id, title, description, release_date, duration
FROM movies
`

type ListMoviesRow struct {
	ID          int32
	Title       string
	Description string
	ReleaseDate time.Time
	Duration    int32
}

func (q *Queries) ListMovies(ctx context.Context) ([]ListMoviesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMoviesRow
	for rows.Next() {
		var i ListMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ReleaseDate,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovie = `-- name: UpdateMovie :exec
UPDATE movies
SET title = $2,
    description = $3,
    release_date = $4,
    duration = $5
WHERE id = $1
`

type UpdateMovieParams struct {
	ID          int32
	Title       string
	Description string
	ReleaseDate time.Time
	Duration    int32
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) error {
	_, err := q.db.ExecContext(ctx, updateMovie,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ReleaseDate,
		arg.Duration,
	)
	return err
}
