services:
  postgres:
    image: postgres:16
    container_name: movies_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema/movie.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  postgres_data: